name: Test

on:

push:

branches:

- main

jobs:

test:

    runs-on: ubuntu-latest

    name: Run tests

    steps:

    - uses: actions/checkout@v3

    - uses: bahmutov/npm-install@v1

    - run: npm run lint  

    - run: npm run test 